## How do these statistics line up by player in relation to the top players/teams (MVPs) of the 2022-2023 season

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pwd

'/Users/christopherbaker_1'

In [4]:
cd /Users/christopherbaker_1/desktop

/Users/christopherbaker_1/Desktop

In [10]:
# read csv file
stats_2023 = pd.read_csv("latest_RAPTOR_by_player.csv")

In [11]:
stats_2023

,player_name,player_id,season,poss,mp,raptor_box_offense,raptor_box_defense,raptor_box_total,raptor_onoff_offense,raptor_onoff_defense,...,raptor_offense,raptor_defense,raptor_total,war_total,war_reg_season,war_playoffs,predator_offense,predator_defense,predator_total,pace_impact
0,Precious Achiuwa,achiupr01,2023,2328,1140,-2.442459,0.605968,-1.836491,1.583854,-3.756532,...,-1.771180,-0.283673,-2.054852,0.400488,0.400488,0.000000,-1.867986,-0.182806,-2.050792,-0.956065
1,Steven Adams,adamsst01,2023,2391,1133,-0.539149,4.174473,3.635324,4.196019,0.186159,...,0.416279,3.550985,3.967264,3.892111,3.892111,0.000000,0.025097,3.570024,3.595120,0.237905
2,Bam Adebayo,adebaba01,2023,6933,3448,-1.905568,2.343398,0.437830,1.584151,2.634869,...,-1.279140,2.528053,1.248914,7.035148,5.692164,1.342984,-0.809324,2.539526,1.730202,-0.443789
3,Ochai Agbaji,agbajoc01,2023,2604,1209,-1.323938,-2.198396,-3.522334,0.637793,-0.569349,...,-1.010696,-1.964927,-2.975622,-0.139469,-0.139469,0.000000,-1.145865,-2.506387,-3.652252,0.216216
4,Santi Aldama,aldamsa01,2023,3824,1783,-1.022699,-0.407462,-1.430161,-0.169196,-1.337527,...,-0.907095,-0.675487,-1.582582,1.058655,1.159520,-0.100866,-1.245487,-0.165475,-1.410962,-0.035690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,Thaddeus Young,youngth01,2023,1642,795,-1.676276,0.902197,-0.774079,-2.849650,-2.873149,...,-2.048536,0.155497,-1.893039,0.348919,0.348919,0.000000,-1.652834,1.012841,-0.639993,0.385635
537,Trae Young,youngtr01,2023,6020,2771,5.777631,-1.040471,4.737160,-0.108236,-0.287141,...,4.871940,-0.925286,3.946654,9.767050,9.121716,0.645334,5.375346,-1.720146,3.655200,3.000059
538,Omer Yurtseven,yurtsom01,2023,212,99,0.061112,-7.201143,-7.140032,2.697151,-4.393875,...,0.607970,-7.089558,-6.481588,-0.190396,-0.095551,-0.094845,0.069578,-6.208725,-6.139147,0.268438
539,Cody Zeller,zelleco01,2023,801,391,-2.844900,-3.861700,-6.706600,0.774588,-2.275713,...,-2.271127,-3.793705,-6.064831,-0.667251,-0.488714,-0.178537,-2.305684,-3.094797,-5.400481,0.312224
540,Ivica Zubac,zubaciv01,2023,4721,2300,-2.461412,2.429430,-0.031982,0.189055,-2.287532,...,-2.062918,1.589006,-0.473912,2.665541,2.150220,0.515322,-2.522289,1.882625,-0.639664,-0.578707

In [12]:
# finding rows & columns with null values
stats_2023.isnull()

,player_name,player_id,season,poss,mp,raptor_box_offense,raptor_box_defense,raptor_box_total,raptor_onoff_offense,raptor_onoff_defense,...,raptor_offense,raptor_defense,raptor_total,war_total,war_reg_season,war_playoffs,predator_offense,predator_defense,predator_total,pace_impact
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
537,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
538,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
539,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
540,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# fill all null values with 0 
complete_stats_2023 = stats_2023.fillna(0)

In [15]:
stats_2023

,player_name,player_id,season,poss,mp,raptor_box_offense,raptor_box_defense,raptor_box_total,raptor_onoff_offense,raptor_onoff_defense,...,raptor_offense,raptor_defense,raptor_total,war_total,war_reg_season,war_playoffs,predator_offense,predator_defense,predator_total,pace_impact
0,Precious Achiuwa,achiupr01,2023,2328,1140,-2.442459,0.605968,-1.836491,1.583854,-3.756532,...,-1.771180,-0.283673,-2.054852,0.400488,0.400488,0.000000,-1.867986,-0.182806,-2.050792,-0.956065
1,Steven Adams,adamsst01,2023,2391,1133,-0.539149,4.174473,3.635324,4.196019,0.186159,...,0.416279,3.550985,3.967264,3.892111,3.892111,0.000000,0.025097,3.570024,3.595120,0.237905
2,Bam Adebayo,adebaba01,2023,6933,3448,-1.905568,2.343398,0.437830,1.584151,2.634869,...,-1.279140,2.528053,1.248914,7.035148,5.692164,1.342984,-0.809324,2.539526,1.730202,-0.443789
3,Ochai Agbaji,agbajoc01,2023,2604,1209,-1.323938,-2.198396,-3.522334,0.637793,-0.569349,...,-1.010696,-1.964927,-2.975622,-0.139469,-0.139469,0.000000,-1.145865,-2.506387,-3.652252,0.216216
4,Santi Aldama,aldamsa01,2023,3824,1783,-1.022699,-0.407462,-1.430161,-0.169196,-1.337527,...,-0.907095,-0.675487,-1.582582,1.058655,1.159520,-0.100866,-1.245487,-0.165475,-1.410962,-0.035690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,Thaddeus Young,youngth01,2023,1642,795,-1.676276,0.902197,-0.774079,-2.849650,-2.873149,...,-2.048536,0.155497,-1.893039,0.348919,0.348919,0.000000,-1.652834,1.012841,-0.639993,0.385635
537,Trae Young,youngtr01,2023,6020,2771,5.777631,-1.040471,4.737160,-0.108236,-0.287141,...,4.871940,-0.925286,3.946654,9.767050,9.121716,0.645334,5.375346,-1.720146,3.655200,3.000059
538,Omer Yurtseven,yurtsom01,2023,212,99,0.061112,-7.201143,-7.140032,2.697151,-4.393875,...,0.607970,-7.089558,-6.481588,-0.190396,-0.095551,-0.094845,0.069578,-6.208725,-6.139147,0.268438
539,Cody Zeller,zelleco01,2023,801,391,-2.844900,-3.861700,-6.706600,0.774588,-2.275713,...,-2.271127,-3.793705,-6.064831,-0.667251,-0.488714,-0.178537,-2.305684,-3.094797,-5.400481,0.312224
540,Ivica Zubac,zubaciv01,2023,4721,2300,-2.461412,2.429430,-0.031982,0.189055,-2.287532,...,-2.062918,1.589006,-0.473912,2.665541,2.150220,0.515322,-2.522289,1.882625,-0.639664,-0.578707

In [37]:
# categories that describe top players
raptor_war = stats_2023.groupby("player_name")["war_total"].sum()
raptor_war_df = pd.DataFrame(raptor_war)
raptor_war_df = raptor_war_df.sort_values(by="war_total",ascending=False)

raptor_total = stats_2023.groupby("player_name")["raptor_total"].sum()
raptor_total_df = pd.DataFrame(raptor_total)
raptor_total_df = raptor_total_df.sort_values(by="raptor_total",ascending=False)


raptor_offense = stats_2023.groupby("player_name")["raptor_offense"].sum()
raptor_offense_df = pd.DataFrame(raptor_offense)
raptor_offense_df = raptor_offense_df.sort_values(by="raptor_offense",ascending=False)

raptor_defense = stats_2023.groupby("player_name")["raptor_defense"].sum()
raptor_defense_df = pd.DataFrame(raptor_defense)
raptor_defense_df = raptor_defense_df.sort_values(by="raptor_defense",ascending=False)

# add mp to categories to give correct top players

In [30]:
raptor_war_df.head()

               war_total
player_name
Nikola Jokic   25.867186
Joel Embiid    14.224680
Jimmy Butler   13.797291
Luka Doncic    12.984393
Anthony Davis  12.948693

In [34]:
raptor_total_df.head()

                  raptor_total
player_name
Stanley Umude        59.363461
Donovan Williams     43.735640
Jordan Schakel       23.049295
Tyler Dorsey         22.817177
Nikola Jokic         13.218736

In [36]:
raptor_offense_df.head()

                  raptor_offense
player_name
Donovan Williams       23.287300
Tyler Dorsey           13.676097
Stanley Umude          12.363526
Jordan Schakel         11.780005
Nikola Jokic            9.522496

In [38]:
raptor_defense_df.head()

                  raptor_defense
player_name
Stanley Umude          46.999935
Donovan Williams       20.448340
DaQuan Jeffries        19.732778
Alize Johnson          15.117748
Facundo Campazzo       11.904225